MODULE_COMMANDS = {
    "basic": [".basic root-check", ".basic profile", ".basic sect-list"],
    "cultivation": [".fanren on normal", ".fanren on deep", ".fanren status"],
    "sect": [".sect panel", ".sect sign", ".sect teach", ".sect bounty"],
    "tianxing": [
        ".天机盘",
        ".观命",
        ".消劫",
        ".定命 贪狼",
        ".推命 探索",
        ".改命 探索",
    ],
    "breakthrough": [
        ".breakthrough jiedan",
        ".breakthrough yuanying",
        ".breakthrough huashen",
    ],
    "battle": [".battle pvp @目标", ".battle rank", ".battle test", ".battle tower"],
    "artifact": [".状态", ".我的器灵", ".抚摸法宝", ".唤醒器灵", ".一键修理"],
    "inventory": [
        ".inventory bag",
        ".inventory learn 物品",
        ".inventory craft 物品*数量",
    ],
    "fishing": [
        ".渔具铺",
        ".鱼篓",
        ".钓鱼 青溪浅滩 凡饵",
        ".钓鱼状态",
        ".试探咬饵",
        ".提竿",
        ".收竿",
        ".打窝 米糠小窝",
        ".买鱼饵 凡饵 20",
        ".开鱼 青鳞小鲫 1",
    ],
    "small_world": [
        ".小世界",
        ".开辟小世界",
        ".收割香火",
        ".显灵",
        ".神庙",
        ".升级神庙",
        ".护界禁制",
        ".神迹 赈灾",
        ".神迹 布道",
        ".神识淬炼 100",
        ".寄养灵兽 灵兽名",
        ".召回灵兽",
    ],
    "other": [
        ".卜筮问天",
        ".六道轮回盘",
        ".赌石",
        ".押 大 100",
        ".对赌 500",
    ],
    "estate": [
        ".洞府",
        ".升级灵脉",
        ".升级静室",
        ".布置景观 景观名",
        ".上架至万宝阁 物品名",
    ],
    "companion": [
        ".companion search",
        ".companion dream",
        ".companion place",
        ".companion recall",
    ],
    "market": [".market board", ".market auction", ".market bounty", ".market gamble"],
    "stock": [
        ".股市",
        ".大盘",
        ".领股息",
        ".个股 IDX_CODE",
        ".买入 IDX_CODE 金额",
        ".卖出 IDX_CODE 数量",
        ".我的持仓",
        ".融资买入 IDX_CODE 金额",
        ".融资平仓 IDX_CODE 数量",
        ".股市任务",
    ],
    "dungeon": [
        ".开启虚天殿",
        ".加入副本 123",
        ".进入虚天殿",
        ".开启昆吾山",
        ".开启坠魔谷",
        ".开启掩月抢亲",
        ".加入掩月抢亲 123",
        ".掩月抢亲状态",
        ".抢亲抉择 1",
        ".开启落云秘圃",
        ".加入落云秘圃",
        ".落云秘圃状态",
        ".落云抉择 1",
        ".开启苍坤洞府",
        ".加入苍坤洞府",
        ".苍坤洞府状态",
        ".苍坤抉择 1",
    ],
    "diplomacy": [".diplomacy map", ".diplomacy favor 宗门", ".diplomacy ally 宗门"],
    "shop": [".shop open"],
}
